// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: homeaffairspb/homeaffairs.proto

package homeaffairspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CitizenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdNumber string `protobuf:"bytes,1,opt,name=idNumber,proto3" json:"idNumber,omitempty"`
}

func (x *CitizenRequest) Reset() {
	*x = CitizenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homeaffairspb_homeaffairs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CitizenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CitizenRequest) ProtoMessage() {}

func (x *CitizenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_homeaffairspb_homeaffairs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CitizenRequest.ProtoReflect.Descriptor instead.
func (*CitizenRequest) Descriptor() ([]byte, []int) {
	return file_homeaffairspb_homeaffairs_proto_rawDescGZIP(), []int{0}
}

func (x *CitizenRequest) GetIdNumber() string {
	if x != nil {
		return x.IdNumber
	}
	return ""
}

type CitizenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	Surname   string `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Age       int32  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *CitizenResponse) Reset() {
	*x = CitizenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_homeaffairspb_homeaffairs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CitizenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CitizenResponse) ProtoMessage() {}

func (x *CitizenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_homeaffairspb_homeaffairs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CitizenResponse.ProtoReflect.Descriptor instead.
func (*CitizenResponse) Descriptor() ([]byte, []int) {
	return file_homeaffairspb_homeaffairs_proto_rawDescGZIP(), []int{1}
}

func (x *CitizenResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CitizenResponse) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *CitizenResponse) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_homeaffairspb_homeaffairs_proto protoreflect.FileDescriptor

var file_homeaffairspb_homeaffairs_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x68, 0x6f, 0x6d, 0x65, 0x61, 0x66, 0x66, 0x61, 0x69, 0x72, 0x73, 0x70, 0x62, 0x2f,
	0x68, 0x6f, 0x6d, 0x65, 0x61, 0x66, 0x66, 0x61, 0x69, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x2c, 0x0a, 0x0e, 0x43, 0x69, 0x74, 0x69, 0x7a, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22,
	0x5b, 0x0a, 0x0f, 0x43, 0x69, 0x74, 0x69, 0x7a, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x32, 0x40, 0x0a, 0x0b,
	0x48, 0x6f, 0x6d, 0x65, 0x41, 0x66, 0x66, 0x61, 0x69, 0x72, 0x73, 0x12, 0x31, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x43, 0x69, 0x74, 0x69, 0x7a, 0x65, 0x6e, 0x12, 0x0f, 0x2e, 0x43, 0x69, 0x74, 0x69,
	0x7a, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x43, 0x69, 0x74,
	0x69, 0x7a, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12,
	0x5a, 0x10, 0x2e, 0x2f, 0x3b, 0x68, 0x6f, 0x6d, 0x65, 0x61, 0x66, 0x66, 0x61, 0x69, 0x72, 0x73,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_homeaffairspb_homeaffairs_proto_rawDescOnce sync.Once
	file_homeaffairspb_homeaffairs_proto_rawDescData = file_homeaffairspb_homeaffairs_proto_rawDesc
)

func file_homeaffairspb_homeaffairs_proto_rawDescGZIP() []byte {
	file_homeaffairspb_homeaffairs_proto_rawDescOnce.Do(func() {
		file_homeaffairspb_homeaffairs_proto_rawDescData = protoimpl.X.CompressGZIP(file_homeaffairspb_homeaffairs_proto_rawDescData)
	})
	return file_homeaffairspb_homeaffairs_proto_rawDescData
}

var file_homeaffairspb_homeaffairs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_homeaffairspb_homeaffairs_proto_goTypes = []interface{}{
	(*CitizenRequest)(nil),  // 0: CitizenRequest
	(*CitizenResponse)(nil), // 1: CitizenResponse
}
var file_homeaffairspb_homeaffairs_proto_depIdxs = []int32{
	0, // 0: HomeAffairs.GetCitizen:input_type -> CitizenRequest
	1, // 1: HomeAffairs.GetCitizen:output_type -> CitizenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_homeaffairspb_homeaffairs_proto_init() }
func file_homeaffairspb_homeaffairs_proto_init() {
	if File_homeaffairspb_homeaffairs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_homeaffairspb_homeaffairs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CitizenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_homeaffairspb_homeaffairs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CitizenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_homeaffairspb_homeaffairs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_homeaffairspb_homeaffairs_proto_goTypes,
		DependencyIndexes: file_homeaffairspb_homeaffairs_proto_depIdxs,
		MessageInfos:      file_homeaffairspb_homeaffairs_proto_msgTypes,
	}.Build()
	File_homeaffairspb_homeaffairs_proto = out.File
	file_homeaffairspb_homeaffairs_proto_rawDesc = nil
	file_homeaffairspb_homeaffairs_proto_goTypes = nil
	file_homeaffairspb_homeaffairs_proto_depIdxs = nil
}
