FROM golang:1.18-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY ./homeaffairspb ./homeaffairspb
COPY ./client/client.go .

ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -ldflags="-s -w" -o client .

FROM scratch

COPY --from=builder ["/build/client", "/"]

ENTRYPOINT ["/client"]